name: Test suite

on: [pull_request]

jobs:
  build-and-push-route-optimization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build route-optimization-image
        run: docker build packages/route-optimization-jsprit --tag iteam1337/pm-route-optimization-jsprit:latest
      - name: Push route-optimization-image
        run: docker push iteam1337/pm-route-optimization-jsprit:latest
  run-engine-integration-tests:
    needs: build-and-push-route-optimization
    env:
      AMQP_HOST: localhost
    defaults:
      run:
        working-directory: packages/engine_umbrella/
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      route-optmization-jsprit:
        image: iteam1337/pm-route-optimization-jsprit
        env:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: "5672"
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1.6.0
        with:
          otp-version: "24.0"
          elixir-version: "1.12.2"
      - name: Install Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile
      - name: create database
        run: mix setupTestDatabase
      - name: Run tests
        run: mix test
  run-driver-interface-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/driver-interface/
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
  run-engine-server-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/engine-server/
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test


